{"uuid": "4a2ad1ca-ff29-4b70-bd22-7bbbc3a417ae", "children": ["97d471dc-36eb-429b-b567-b73f69aed1b7", "52180184-27d3-4bf7-b4ea-09f6a38c1588", "ce5ef807-9cc7-4563-8135-7362d4b95b03", "ae107dff-f8ae-4817-9ae5-25ee7a0d2740", "ddbc5167-5620-42ea-bacc-41002d93a196", "5f537ff8-5aa5-45d5-9339-23d08163e4d2", "1f2d3f41-5f33-4800-893e-cf52d20bcb3f", "e9450e10-9e37-4ab4-9481-d582aae1c919"], "befores": [{"name": "_xunit_setup_class_fixture_TestFAQ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 854, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\python.py\", line 776, in _call_with_optional_argument\n    func(arg)\n  File \"C:\\Users\\user\\Desktop\\Project_4\\tests\\test_faq.py\", line 10, in setup_class\n    cls.driver = webdriver.Firefox()\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 180, in __init__\n    RemoteWebDriver.__init__(\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1666353437456, "stop": 1666353440815}], "start": 1666353437456, "stop": 1666353441549}